### ISSUE TITLE
Error in LG list

### ISSUE THREAD

**Issue by BitFliper** [Perflyst/PiHoleBlocklist#134]
It looks like the following entry under LG tv's is incorrect:
lgad.cjpowercast.com.edgesuite.net

I think it should be two entries:
lgad.cjpowercast.com
edgesuite.net

**Comment by iboolka** [comment]
> It looks like the following entry under LG tv's is incorrect: 
>lgad.cjpowercast.com.edgesuite.net
> 
> I think it should be two entries:
> lgad.cjpowercast.com 
>edgesuite.net

I think this is the correct entry because server is answering:

- lgad.cjpowercast.com.edgesuite.net
Server:		8.8.8.8
Address:	8.8.8.8#53
Non-authoritative answer:
lgad.cjpowercast.com.edgesuite.net	canonical name = a1017.w73.akamai.net.
Name:	a1017.w73.akamai.net
Address: 23.67.33.198
Name:	a1017.w73.akamai.net
Address: 23.67.33.202

But no answer if:

- lgad.cjpowercast.com
Server:		8.8.8.8
Address:	8.8.8.8#53
** server can't find lgad.cjpowercast.com: NXDOMAIN

- edgesuite.net
Server:		10.0.0.5
Address:	10.0.0.5#53
Non-authoritative answer:
*** Can't find edgesuite.net: No answer

**Comment by AJCxZ0** [comment]
Note that _edgesuite.net_ is a domain used by Akamai for their CDN. It has no A or CNAME record and nor does _lgad.cjpowercast.com_.

The record to block is correct: lgad.cjpowercast.com.edgesuite.net.

**Comment by BitFliper** [comment]
Ok, thank you for looking into it. I will close.
