### ISSUE TITLE
LG Content Store blocked

### ISSUE THREAD

**Issue by PedroLamas** [Perflyst/PiHoleBlocklist#53]
My LG TV Content Store was blocked, I found that the domain gb.lgtvsdp.com is required for it to work so probably better to whitelist all of the *.lgtvsdp.com ?

**Comment by Perflyst** [comment]
Are you using pihole or adguard?

**Comment by PedroLamas** [comment]
Currently, I'm using the latest version of AdGuard Home.

**Comment by DandelionSprout** [comment]
Which TV model do you have, and what does the breakage and/or error note look like?

**Comment by PedroLamas** [comment]
@DandelionSprout my LG TV model is OLED55C7V.

This is what happens if I use this list with all current rules and open the LG Content Store app on the TV:

![image](https://user-images.githubusercontent.com/85504/82715960-25663b00-9c8d-11ea-8ac1-82a93f8526cf.png)

Here's the Adguard Home logs:

![image](https://user-images.githubusercontent.com/85504/82715923-0ff11100-9c8d-11ea-84f0-ee00eaaf2b99.png)

My quick fix for this problem is to add `@@||gb.lgtvsdp.com^` to the Custom filtering rules, after that the LG Content Store works again!

**Comment by DandelionSprout** [comment]
Since the TV model differs substantially from my own unaffected LG TV (LG 43UH603V), and since `gb.lgtvsdp.com` changes its first two letters depending on the user's country (presuming you're in the UK at the moment), it'd sadly actually be the best idea to whitelist *all* `[country code].lgtvsdp.com` domains.

I've attempted such a fix in #57.

**Comment by PedroLamas** [comment]
Just tried the file on that branch, works fine for my TV!

**Comment by Perflyst** [comment]
Closed via #57
