### ISSUE TITLE
ad in home screen / apps dont download

### ISSUE THREAD

**Issue by ideasman69** [Perflyst/PiHoleBlocklist#74]
Thanks heaps for this list, unfortunately I still get the occasional ad along the bottom home bar thingy when pressing the home button on a 2020 "the frame" samsung.

I also can't download apps from the samsung app store, it complains about not being connected. i need to disable the pihole, restart the tv, get the app, then re-enable pihole.

i've tried watching the query log in pihole to figure out which one is getting blocked but can't track it down...

**Comment by s1mwest** [comment]
Hi, my Samsung Q9FN constantly tries cdn.samsungcloudsolution.com, which is Samsung's content delivery network.  Their apps (and ads) come from here because it is a resilient/load balanced cloud.  Maybe you can whitelist this address to test downloading apps?

Also, to speed things up when you are testing/diagnosing etc. can you use a different network that doesn't have any filtering? e.g. My TV is usually on a wired network via my own DNS filtering (which uses this awesome list), so I use the TV menu to switch to a Wi-Fi network that doesn't have filtering e.g. my iPhone hotspot.  Using this method forces the TV to clear it's DNS cache and when you switch back to wired.

Ads still showing and apps not downloading or working are sadly the hurdles encountered when using a method to block the manufacturer's telemetry etc. Generally, using a blocklist is so much easier when you just want your telly to be a telly and still get software updates.  This is how it was for me until the missus wanted iPlayer, All4 etc. :)

**Comment by Perflyst** [comment]
Could you catch any further domains so far?
